### PR TITLE
[+] Cinnamon support

### PR DESCRIPTION
**Pull request by aleskovets**
Hi,

This is a little patch that adds a support for cinanmon screen lock.

--Anton

### CODE REVIEW

**Comment by costela** [comment]
Thanks for the patch! Could you maybe fix the indentation of the DBusGProxy declarations to match the rest of the file (tabs instead of spaces)?

**Comment by aleskovets** [comment]
Line indentation is updated and incorporated into the single commit (d22b904).

**Comment by aleskovets** [comment]
Just wonder if there is some issue with this patch?

**Comment by costela** [comment]
Nope, sorry, just went under the radar. Merged! Thanks!

**Comment by aleskovets** [comment]
Great! Thanks!

**Pull request merged**
